# load packages

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
from palmerpenguins import load_penguins

# load dataset palmerpenguins

In [2]:
penguins = load_penguins()
dt       = penguins.dropna()
dt.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
4       3450.0  female  2007  
5       3650.0    male  2007

scifit-learn 모델들은 수치형 데이터를 넣어야 하는 듯 하여 범주형 데이터를 더미 코딩 한다

In [14]:
dt_dummy = pd.get_dummies(dt, columns = ['species', 'island'], drop_first = True)
dt_dummy

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex  \
0              39.1           18.7              181.0       3750.0    male   
1              39.5           17.4              186.0       3800.0  female   
2              40.3           18.0              195.0       3250.0  female   
4              36.7           19.3              193.0       3450.0  female   
5              39.3           20.6              190.0       3650.0    male   
..              ...            ...                ...          ...     ...   
339            55.8           19.8              207.0       4000.0    male   
340            43.5           18.1              202.0       3400.0  female   
341            49.6           18.2              193.0       3775.0    male   
342            50.8           19.0              210.0       4100.0    male   
343            50.2           18.7              198.0       3775.0  female   

     year  species_Chinstrap  species_Gentoo  island_Dream  island_Torgersen  
0    2007                  0               0             0                 1  
1    2007                  0               0             0                 1  
2    2007                  0               0             0                 1  
4    2007                  0               0             0                 1  
5    2007                  0               0             0                 1  
..    ...                ...             ...           ...               ...  
339  2009                  1               0             1                 0  
340  2009                  1               0             1                 0  
341  2009                  1               0             1                 0  
342  2009                  1               0             1                 0  
343  2009                  1               0             1                 0  

[333 rows x 10 columns]

In [22]:
from sklearn.model_selection import train_test_split
x = dt_dummy.drop('sex', axis = 1)
y = dt_dummy.sex
#test data size는 전체의 25%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 123)

## 1. KNN

In [28]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

# 
knn = KNeighborsClassifier(n_neighbors = 5)
# model training
knn_fit = knn.fit(x_train, y_train)
# testing the model
dt_pred = knn.predict(x_test)
confusion_matrix(y_test, dt_pred)

array([[29,  7],
       [16, 32]])

## 2. Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

# 
DCTr = DecisionTreeClassifier(criterion='entropy', max_depth = 4, random_state = 0)
# model training
DCTr_fit = DCTr.fit(x_train, y_train)
# testing the model
dt_pred = DCTr.predict(x_test)
confusion_matrix(y_test, dt_pred)


array([[34,  2],
       [15, 33]])

## 3. ANN(Artificial Neural Network)

In [45]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
# model training
mlp_fit = mlp.fit(x_train, y_train)
# testing the model
dt_pred = mlp.predict(x_test)
confusion_matrix(y_test, dt_pred)

array([[24, 12],
       [28, 20]])

## 4. SVM(Support Vector Machine)

In [37]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

svc = SVC(kernel = "linear")
# model training
svc_fit = svc.fit(x_train, y_train)
# testing the model
dt_pred = svc.predict(x_test)
confusion_matrix(y_test, dt_pred)

array([[34,  2],
       [10, 38]])

## 5. Random Forest

In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

rf = RandomForestClassifier()
# model training
rf_fit = rf.fit(x_train, y_train)
# testing the model
dt_pred = rf.predict(x_test)
confusion_matrix(y_test, dt_pred)

array([[33,  3],
       [ 9, 39]])

## 6. Naive Beyes

In [39]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

gb = GaussianNB()
# model training
gb_fit = gb.fit(x_train, y_train)
# testing the model
gb_pred = gb.predict(x_test)
confusion_matrix(y_test, dt_pred)


array([[33,  3],
       [ 9, 39]])